---
# tasks file for ansible-minecraft
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install GnuPG
  ansible.builtin.package:
    name: gnupg
    state: present

- name: Ensure Java key is on remote
  ansible.builtin.apt_key:
    url: "{{ minecraft_java_deb_key }}"
    keyring: /usr/share/keyrings/corretto-keyring.gpg
    state: present

- name: Ensure Java repository is on remote
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/java.list
    content: "{{ minecraft_java_deb_repo }}"
    owner: root
    group: root
    mode: "0644"

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install Java packages
  ansible.builtin.package:
    name:
      - "{{ minecraft_java_package }}"
      - libxi6
      - libxtst6
      - libxrender1
    state: present

- name: Get Paper jar file
  ansible.builtin.get_url:
    url: "https://api.papermc.io/v2/projects/paper/versions/{{ minecraft_paper_version }}/builds/{{ minecraft_paper_build }}/downloads/paper-{{ minecraft_paper_version }}-{{ minecraft_paper_build }}.jar"
    dest: /root/paper-{{ minecraft_paper_version }}-{{ minecraft_paper_build }}.jar
    mode: "0644"
  notify: Restart Minecraft

- name: Ensure EULA file is present on remote
  ansible.builtin.copy:
    src: eula.txt
    dest: /root/eula.txt
    mode: "0644"
    owner: root
    group: root
  notify: Restart Minecraft

- name: Ensure templates are deployed on remote
  ansible.builtin.template:
    src: /root/server.properties
    dest: "{{ minecraft_properties_template }}"
    mode: "0644"
    owner: root
    group: root
  notify: Restart Minecraft

- name: Ensure Minecraft service file is on remote (systemd)
  ansible.builtin.template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart Minecraft

- name: Ensure Minecraft service is enabled and started
  ansible.builtin.systemd:
    name: minecraft
    state: started
    enabled: true
