---
# tasks file for ansible-minecraft
- name: Update cache if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install Java and git package
  ansible.builtin.package:
    name: "openjdk-{{ minecraft_java_version }}-jre-headless"
    state: present

- name: Get Paper jar file
  ansible.builtin.get_url:
    url: "https://api.papermc.io/v2/projects/paper/versions/{{ minecraft_paper_version }}/builds/{{ minecraft_paper_build }}/downloads/paper-{{ minecraft_paper_version }}-{{ minecraft_paper_build }}.jar"
    dest: /root/paper-{{ minecraft_paper_version }}-{{ minecraft_paper_build }}.jar
    mode: "0644"
  notify: Restart minecraft service

- name: Ensure minecraft service file is on remote (systemd)
  ansible.builtin.template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    mode: "0664"
    owner: root
    group: root

- name: Ensure minecraft service is enabled and started
  ansible.builtin.service:
    name: minecraft
    state: started
    enabled: true
